sudo: false
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - rbx
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
    - rvm: jruby-head

